# Generated by Django 5.0.7 on 2026-05-30 09:54

import apps.alerts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '__first__'),
        ('organizations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('rule_type', models.CharField(choices=[('people_count', 'People Count'), ('crowd_threshold', 'Crowd Threshold'), ('queue_length', 'Queue Length'), ('dwell_time', 'Dwell Time'), ('intrusion', 'Intrusion (after-hours)'), ('line_crossing', 'Line Crossing'), ('loitering', 'Loitering'), ('abandoned_object', 'Abandoned Object'), ('parking_occupied', 'Parking Slot Occupied'), ('parking_illegal', 'Illegal Parking'), ('parking_duration', 'Parking Duration Exceeded'), ('camera_offline', 'Camera Offline')], default='people_count', max_length=32)),
                ('threshold_value', models.FloatField()),
                ('condition', models.CharField(choices=[('greater_than', 'Greater than'), ('less_than', 'Less than'), ('equals', 'Equals')], default='greater_than', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown_seconds', models.PositiveIntegerField(default=300, help_text='Minimum seconds between duplicate alerts.')),
                ('notification_email', models.EmailField(blank=True, help_text='Legacy single-recipient email. Prefer channels/channel_config.', max_length=254)),
                ('channels', models.JSONField(blank=True, default=list, help_text='List of channels: ["email","slack","discord","webhook","sms"].', validators=[apps.alerts.models._validate_channels])),
                ('channel_config', models.JSONField(blank=True, default=dict, help_text='Per-channel config, e.g. {"slack": {"webhook_url": "..."}, "discord": {"webhook_url": "..."}, "webhook": {"url": "...", "auth_token": "..."}, "email": {"to": "ops@example.com"}, "sms": {"to": "+15551234567"}}')),
                ('active_from', models.CharField(blank=True, help_text='HH:MM, e.g. 18:00', max_length=5)),
                ('active_to', models.CharField(blank=True, help_text='HH:MM, e.g. 20:00', max_length=5)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='List of ISO weekday ints 1=Mon..7=Sun. Empty = every day.')),
                ('camera', models.ForeignKey(blank=True, help_text='Null = rule applies to all cameras in the org.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='cameras.camera')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='new', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ai_summary', models.TextField(blank=True, help_text='Optional LLM-generated human summary. Populated asynchronously if the organization has an active AI provider configured.')),
                ('clip_path', models.CharField(blank=True, help_text='Relative path to 1-5 s evidence clip under MEDIA_ROOT. Optional.', max_length=500)),
                ('clip_duration_s', models.PositiveSmallIntegerField(default=0)),
                ('delivery_log', models.JSONField(blank=True, default=dict, help_text='Per-channel delivery results, e.g. {"slack": {"ok": true}}')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cameras.camera')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='organizations.organization')),
                ('alert_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.alertrule')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', '-created_at'], name='alerts_aler_organiz_d8cd5c_idx'), models.Index(fields=['status'], name='alerts_aler_status_2a92cb_idx')],
            },
        ),
    ]
